spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_shop
    username: root
    password: khongcoviecgikho
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true
server:
  port: 8888