spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=book_shop
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true
server:
  port: 8888